name: release

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn build
      - name: CommitVersion
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'github ci'
          message: 'chore(ci): publish npm'