name: release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn add classnames
      - run: sed -i "s/npm.taobao/npmjs/g" yarn.lock
      - name: build
        run: yarn build
